### ISSUE TITLE
Funzionalità del Software

### ISSUE THREAD

**Issue by GabrieleMasinari27** [FilippoBolis/Progetto_ING.Software_23_24#12]
Nel README ho aggiunto una parte che parla delle funzionalità del sistema, qualcosa ho aggiunto, ma volevo chiedervi di vederlo e nel caso dirmi cosa aggiungere

**Comment by Gabriele-Mazzoleni** [comment]
L'unica cosa che modificherei è che CreateDB crea il database, il file vero e proprio di database si chiama semplicemente "db.db3"

**Comment by GabrieleMasinari27** [comment]
ok, l'ho modificato fatemi sapere
