### ISSUE TITLE
Aggiunta nel database

### ISSUE THREAD

**Issue by FilippoBolis** [FilippoBolis/Progetto_ING.Software_23_24#2]
Riesci a aggiungere nel db la posizione del paziente e già che ci sei a cambiare il grado di urgenza da int a string? Così mettiamo direttamente rosso verde e giallo (se pensi che sia una buona idea) grazie gab

**Comment by Gabriele-Mazzoleni** [comment]
Ok, ho modificato urgenza in string, con valori ammissibili "verde", "giallo" e "rosso", poi ho sostituito il booleano "in_attesa" con lo string "posizione": all'inserimento nel DB ogni paziente è "in Pronto Soccorso", quando viene inserita una diaria medica a un paziente la sua posizione diventa "in attesa" e quando gli viene assegnato il letto diventa "in reparto"
